import { useEffect,useState } from 'react';
import { api } from '../api';
import { PLAN_CATALOG } from '../domain/plans';

const money=(minor:number|null)=>minor==null?'Contact us':new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(minor/100);

export function BillingCenter({organizationId,onBrandingChange}:{organizationId:string;onBrandingChange?:(removed:boolean)=>void}){
 const [state,setState]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(!organizationId)return;try{const next=await api.billing.status(organizationId);setState(next);onBrandingChange?.(Boolean(next.brandingRemoved));}catch(e){setMessage(String(e).replace(/^Error:\s*/,''))}}
 useEffect(()=>{void load()},[organizationId]);
 async function upgrade(plan:'starter'|'pro'|'business'){setBusy(true);setMessage('');try{const result=await api.billing.requestUpgrade(organizationId,plan,1);setState((s:any)=>({...s,pendingRequest:result.request,bank:result.bank}));setMessage('Upgrade request created. Transfer to the account below; activation happens only after Timzee Corp approves it.');}catch(e){setMessage(String(e).replace(/^Error:\s*/,''))}finally{setBusy(false)}}
 const current=state?.subscription?.plan_code??'free';
 return <><div className="page-head"><div><span className="eyebrow">PLANS & BILLING</span><h1>Pay for growth, not for access to your own records.</h1><p>Core business records remain useful on Free. Higher plans unlock capacity, AI, WhatsApp automation, advanced accounting, APIs and white-label branding.</p></div><span className="status good">{String(current).toUpperCase()}</span></div>
 {message&&<section className="panel"><strong>{message}</strong></section>}
 {state?.pendingRequest&&<section className="panel billing-pending"><span className="eyebrow">AWAITING TIMZEE CORP APPROVAL</span><h2>{String(state.pendingRequest.requested_plan).toUpperCase()} · {money(Number(state.pendingRequest.amount_minor))}</h2>{state.bank?<p>Transfer to <strong>{state.bank.bankName}</strong> · <strong>{state.bank.accountNumber}</strong> · {state.bank.accountName}. Keep your bank receipt for your own records; THE VERGE does not store card details.</p>:<p>Bank details are not configured yet. Do not transfer until they appear here.</p>}</section>}
 <div className="plan-grid">{(['free','starter','pro','business'] as const).map(code=>{const plan=PLAN_CATALOG[code];return <section className={code===current?'panel plan-card current':'panel plan-card'} key={code}><span className="eyebrow">{plan.name.toUpperCase()}</span><h2>{money(plan.monthlyMinor)}<small>/month</small></h2><p><strong>{plan.limits.products==null?'Unlimited':plan.limits.products}</strong> products · <strong>{plan.limits.locations==null?'Unlimited':plan.limits.locations}</strong> location{plan.limits.locations===1?'':'s'} · <strong>{plan.limits.staff==null?'Unlimited':plan.limits.staff}</strong> staff</p><p>{plan.limits.aiMessages?plan.limits.aiMessages+' AI messages/month':'AI not included'} · {plan.limits.whatsappMessages?plan.limits.whatsappMessages+' WhatsApp automation messages/month':'WhatsApp AI not included'}</p>{plan.whiteLabel&&<p><strong>White-label:</strong> remove “Powered by Timzee Corp” while the subscription is active.</p>}{code!=='free'&&code!==current&&<button className="primary" disabled={busy||Boolean(state?.pendingRequest)} onClick={()=>void upgrade(code)}>Request {plan.name}</button>}</section>})}</div>
 <section className="panel"><span className="eyebrow">ENTERPRISE</span><h2>For chains and very high-volume operations</h2><p>Custom location/staff/AI limits, integrations, rollout support and infrastructure planning. Enterprise activation remains manually approved.</p></section></>;
}

export function PlatformBillingAdmin(){
 const [requests,setRequests]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setRequests((await api.adminBilling.list()).requests)}catch(e){setMessage(String(e).replace(/^Error:\s*/,''))}}
 useEffect(()=>{void load()},[]);
 async function decide(id:string,decision:'approve'|'reject'){setBusy(true);try{await api.adminBilling.decide(id,decision);setRequests(r=>r.filter(x=>x.id!==id));setMessage(decision==='approve'?'Subscription approved. Plan, entitlements and expiry are active server-side.':'Upgrade request rejected.')}catch(e){setMessage(String(e).replace(/^Error:\s*/,''))}finally{setBusy(false)}}
 return <><div className="page-head"><div><span className="eyebrow">TIMZEE CORP ADMIN</span><h1>Manual billing approvals.</h1><p>When your bank alert arrives, choose the matching business request and approve it. Approval is locked, auditable and server-authoritative.</p></div></div>{message&&<section className="panel"><strong>{message}</strong></section>}<section className="panel"><h2>Pending upgrades</h2>{requests.map(r=><div className="list-row" key={r.id}><div><strong>{r.businessName}</strong><span>{r.industry||'Business'} · {String(r.requestedPlan).toUpperCase()} · {money(Number(r.amountMinor))} · {r.months} month{Number(r.months)===1?'':'s'}</span></div><div className="row-actions"><button className="secondary" disabled={busy} onClick={()=>void decide(r.id,'reject')}>Reject</button><button className="primary" disabled={busy} onClick={()=>void decide(r.id,'approve')}>Approve</button></div></div>)}{!requests.length&&<div className="empty">No pending upgrade requests.</div>}</section></>;
}
