import type { VercelRequest,VercelResponse } from '@vercel/node';
import { transactionPool,db } from '../_db'; import { json,method,requireSameOrigin,requireUser } from '../_http'; import { requirePlatformAdmin } from '../_platform';
const ENT:Record<string,string[]>={starter:['personal.finance','business.core','inventory.basic','inventory.advanced','pos','industry.modules','ai.basic'],pro:['personal.finance','business.core','inventory.basic','inventory.advanced','pos','multi_location','industry.modules','advanced_accounting','ai.basic','ai.business_insights','whatsapp','api.read'],business:['personal.finance','business.core','inventory.basic','inventory.advanced','pos','multi_location','industry.modules','advanced_accounting','ai.basic','ai.business_insights','whatsapp','api.read','api.write','webhooks','branding.remove'],enterprise:['personal.finance','business.core','inventory.basic','inventory.advanced','pos','multi_location','industry.modules','advanced_accounting','ai.basic','ai.business_insights','whatsapp','api.read','api.write','webhooks','branding.remove']};
export default async function handler(req:VercelRequest,res:VercelResponse){
 if(!method(req,res,['GET','POST']))return;const user=await requireUser(req,res);if(!user||!requirePlatformAdmin(user,res))return;
 if(req.method==='GET'){const rows=await db()`select r.id,r.organization_id as "organizationId",o.name as "businessName",o.industry,r.requested_plan as "requestedPlan",r.amount_minor as "amountMinor",r.currency,r.billing_cycle_months as "months",r.created_at as "createdAt" from billing_upgrade_requests r join organizations o on o.id=r.organization_id where r.status='pending' order by r.created_at asc limit 200`;return json(res,200,{requests:rows});}
 if(!requireSameOrigin(req,res))return;const requestId=String(req.body?.requestId??''),decision=String(req.body?.decision??'');if(!requestId||!['approve','reject'].includes(decision))return json(res,400,{error:'invalid_decision'});
 const pool=transactionPool();try{await pool.query('BEGIN');const locked=await pool.query("select * from billing_upgrade_requests where id=$1 and status='pending' for update",[requestId]);if(!locked.rowCount){await pool.query('ROLLBACK');return json(res,409,{error:'request_not_pending'});}const r=locked.rows[0] as any;
 if(decision==='reject'){await pool.query("update billing_upgrade_requests set status='rejected',decided_by=$2,decided_at=now() where id=$1",[requestId,user.id]);await pool.query('COMMIT');return json(res,200,{ok:true,status:'rejected'});}
 const months=Math.max(1,Math.min(24,Number(r.billing_cycle_months)||1)),plan=String(r.requested_plan),ents=ENT[plan]??[];
 await pool.query("update subscriptions set status='canceled',updated_at=now() where organization_id=$1 and status in ('trialing','active','grace','past_due')",[r.organization_id]);
 const sub=await pool.query("insert into subscriptions(organization_id,plan_code,status,provider,current_period_start,current_period_end,approved_by,approval_request_id,billing_cycle_months) values($1,$2,'active','manual_bank',now(),now()+($3::int*interval '1 month'),$4,$5,$3) returning id,current_period_end",[r.organization_id,plan,months,user.id,requestId]);
 await pool.query("delete from entitlements where organization_id=$1 and source='plan'",[r.organization_id]);for(const capability of ents){await pool.query("insert into entitlements(organization_id,capability,effect,source,starts_at,expires_at,created_by,reason) values($1,$2,'allow','plan',now(),$3,$4,$5)",[r.organization_id,capability,sub.rows[0].current_period_end,user.id,'Approved '+plan+' subscription']);}
 await pool.query("update billing_upgrade_requests set status='approved',decided_by=$2,decided_at=now() where id=$1",[requestId,user.id]);await pool.query("insert into audit_events(organization_id,actor_user_id,action,entity_type,entity_id,after_data) values($1,$2,'billing.upgrade_approved','subscription',$3,$4::jsonb)",[r.organization_id,user.id,sub.rows[0].id,JSON.stringify({plan,months,requestId})]);await pool.query('COMMIT');return json(res,200,{ok:true,status:'approved',plan,currentPeriodEnd:sub.rows[0].current_period_end});
 }catch{await pool.query('ROLLBACK').catch(()=>undefined);return json(res,500,{error:'internal_error'});}finally{await pool.end();}
}